# Generated by Django 4.2.6 on 2023-10-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
